In [79]:
import pandas as pd

In [80]:
# TODO
# find out which track_ids have spectrogram data
# only take sentiment value from songs which have track_ids in spectrogram data
# merge the sentiment data into the final dataset

lyrics_with_trackid = pd.read_csv("lyrics_with_track_id.txt")
lyrics_with_trackid.drop(columns=['Unnamed: 0'], inplace=True)
lyrics_with_trackid

Artist                                     Song  \
0                    Kidz Bop Kids                             Ghostbusters   
1     Creedence Clearwater Revival              Have You Ever Seen The Rain   
2                     All Time Low                          Blinding Lights   
3                         Bastille                                  Pompeii   
4                      Bryan Adams                            Summer Of '69   
...                            ...                                      ...   
8729                 High Contrast                          Calling My Name   
8730              Paul Kalkbrenner                                     Tief   
8731                     Hypocrisy                            A Coming Race   
8732                   Chloe Agnew                                    Sigma   
8733        Dan Vapid & the Cheats  I Wanna Go to Machu Picchu Before I Die   

                                                 Lyrics  \
0     ['ghostbusters', 'theres', 'somethin', 'strang...   
1     ['ever', 'seen', 'rain', 'someone', 'told', 'l...   
2     ['blinding', 'lights', 'ive', 'tryna', 'call',...   
3     ['phasa', 'thaiespaolportugusitalianopompeii',...   
4     ['summer', 'got', 'first', 'real', 'sixstring'...   
...                                                 ...   
8729  ['contributorswhy', 'hey', 'yo', 'glamma', 'sa...   
8730  ['contributortief', 'deep', 'deep', 'deep', 'd...   
8731  ['contributorsa', 'coming', 'race', 'searching...   
8732  ['contributorssigma', 'ar', 'thoir', 'comharth...   
8733  ['contributorsi', 'wanna', 'go', 'machu', 'pic...   

                    track_id  
0     5IWLGZJR6d8pl5a5tka18u  
1     49oArb5U9DsUXpPSjDPsob  
2     3bkgyThZ4ImhlQNgVRo850  
3     3oaqIiIIu9KUrfqE4AeT93  
4     1zzwcBhUh3TqB2sVJWH84i  
...                      ...  
8729  6x0LElzW1utVgphlTnqsX5  
8730  6PWDT5ZY8Fz5AZTu9CAeTy  
8731  7KDZ0tye2U1ImgVbr36eKp  
8732  7oqZVbE2W4MCoMS34PPDr3  
8733  3mUfADjtWU3XnQW2FPtBch  

[8734 rows x 4 columns]

In [81]:
original_dataset = pd.read_csv("dataset.csv")
original_dataset.drop(columns=['Unnamed: 0'], inplace=True)
original_dataset

track_id                 artists  \
0       5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino   
1       4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward   
2       1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN   
3       6lfxq3CG4xtTiEg7opyCyx            Kina Grannis   
4       5vjLSffimiIP26QG5WcN2K        Chord Overstreet   
...                        ...                     ...   
113995  2C3TZjDRiAzdyViavDJ217           Rainy Lullaby   
113996  1hIz5L4IB9hN3WRYPOCGPw           Rainy Lullaby   
113997  6x8ZfSoqDjuNa5SVP5QjvX           Cesária Evora   
113998  2e6sXL2bYv4bSz6VTdnfLs        Michael W. Smith   
113999  2hETkH7cOfqmz3LqZDHZf5           Cesária Evora   

                                               album_name  \
0                                                  Comedy   
1                                        Ghost (Acoustic)   
2                                          To Begin Again   
3       Crazy Rich Asians (Original Motion Picture Sou...   
4                                                 Hold On   
...                                                   ...   
113995  #mindfulness - Soft Rain for Mindful Meditatio...   
113996  #mindfulness - Soft Rain for Mindful Meditatio...   
113997                                            Best Of   
113998                                  Change Your World   
113999                                     Miss Perfumado   

                        track_name  popularity  duration_ms  explicit  \
0                           Comedy          73       230666     False   
1                 Ghost - Acoustic          55       149610     False   
2                   To Begin Again          57       210826     False   
3       Can't Help Falling In Love          71       201933     False   
4                          Hold On          82       198853     False   
...                            ...         ...          ...       ...   
113995         Sleep My Little Boy          21       384999     False   
113996            Water Into Light          22       385000     False   
113997              Miss Perfumado          22       271466     False   
113998                     Friends          41       283893     False   
113999                   Barbincor          22       241826     False   

        danceability  energy  key  loudness  mode  speechiness  acousticness  \
0              0.676  0.4610    1    -6.746     0       0.1430        0.0322   
1              0.420  0.1660    1   -17.235     1       0.0763        0.9240   
2              0.438  0.3590    0    -9.734     1       0.0557        0.2100   
3              0.266  0.0596    0   -18.515     1       0.0363        0.9050   
4              0.618  0.4430    2    -9.681     1       0.0526        0.4690   
...              ...     ...  ...       ...   ...          ...           ...   
113995         0.172  0.2350    5   -16.393     1       0.0422        0.6400   
113996         0.174  0.1170    0   -18.318     0       0.0401        0.9940   
113997         0.629  0.3290    0   -10.895     0       0.0420        0.8670   
113998         0.587  0.5060    7   -10.889     1       0.0297        0.3810   
113999         0.526  0.4870    1   -10.204     0       0.0725        0.6810   

        instrumentalness  liveness  valence    tempo  time_signature  \
0               0.000001    0.3580   0.7150   87.917               4   
1               0.000006    0.1010   0.2670   77.489               4   
2               0.000000    0.1170   0.1200   76.332               4   
3               0.000071    0.1320   0.1430  181.740               3   
4               0.000000    0.0829   0.1670  119.949               4   
...                  ...       ...      ...      ...             ...   
113995          0.928000    0.0863   0.0339  125.995               5   
113996          0.976000    0.1050   0.0350   85.239               4   
113997          0.000000    0.0839   0.7430  132.378               4   
113998          0.000000    0.2700

In [82]:
original_dataset_with_lyric_data = original_dataset[original_dataset['track_id'].isin(lyrics_with_trackid['track_id'])]
original_dataset_with_lyric_data

track_id                  artists  \
25      6D33wCKzWtNEgOovgeVJ7r               Jason Mraz   
29      2qESE1ZeWly7I3YjyTXmXh               Jason Mraz   
1302    1Wb09hTo6O41UzdOq7Pd2i              The Bamboos   
1452    0rnDmgcZvn9WPsOPqHbt16                  Osibisa   
1708    2yLm7Y9foI71By8rAdYsFE               Dos Santos   
...                        ...                      ...   
113375  2YEJL2fwTq6RpH5PtdQfge         Michael W. Smith   
113381  7GwYyLNFyAsSsmt2aa0z6u         Michael W. Smith   
113504  5UjaOsrdoI4shw9gM2eNPC  Buena Vista Social Club   
113600  3okCsBWWv7okRgaTnMQ2Fp  Buena Vista Social Club   
113804  11TMcTS3iao1dvMogUSQVk  Buena Vista Social Club   

                      album_name             track_name  popularity  \
25              Mellow Adult Pop             Bella Luna           1   
29        Perfect Christmas Hits      Winter Wonderland           0   
1302    Hard Up (Deluxe Version)                Hard Up          12   
1452                  Ojah Awake             Ojah Awake           9   
1708                  Dos Santos            El Pescador          17   
...                          ...                    ...         ...   
113375         Christmas at Home           God with God           1   
113381         Christmas at Home       Freeze The Frame           1   
113504   Buena Vista Social Club      El Cuarto de Tula          14   
113600   Buena Vista Social Club          Dos Gardenias          13   
113804   Buena Vista Social Club  De Camino a la Vereda          11   

        duration_ms  explicit  danceability  energy  key  loudness  mode  \
25           302346     False         0.755   0.454    9    -9.609     0   
29           131760     False         0.620   0.309    5    -9.209     1   
1302         255227     False         0.782   0.922   11    -4.028     0   
1452         296093     False         0.581   0.709    2   -13.307     1   
1708         213186     False         0.562   0.722    4    -5.625     0   
...             ...       ...           ...     ...  ...       ...   ...   
113375       250859     False         0.226   0.388    8    -8.440     1   
113381       231873     False         0.392   0.285    5   -11.236     1   
113504       445426     False         0.546   0.715    9   -11.927     1   
113600       184026     False         0.569   0.205    4   -16.741     0   
113804       303973     False         0.630   0.462    3   -10.792     1   

        speechiness  acousticness  instrumentalness  liveness  valence  \
25           0.0352       0.75700          0.000000    0.2360    0.330   
29           0.0495       0.78800          0.000000    0.1460    0.664   
1302         0.0497       0.00655          0.011800    0.0728    0.761   
1452         0.0436       0.02680          0.232000    0.0398    0.816   
1708         0.0280       0.01320          0.897000    0.1140    0.887   
...             ...           ...               ...       ...      ...   
113375       0.0314       0.53500          0.000000    0.1030    0.158   
113381       0.0309       0.69400          0.000000    0.1100    0.212   
113504       0.0459       0.62100          0.000218    0.2940    0.850   
113600       0.0382       0.83300          0.000140    0.0935    0.518   
113804       0.0406       0.84900          0.000186    0.1250    0.963   

          tempo  time_signature  track_genre  
25      120.060               4     acoustic  
29      145.363               4     acoustic  
1302    104.015               4     afrobeat  
1452    132.096               4     afrobeat  
1708    100.747               4     afrobeat  
...         ...             ...          ...  
113375  114.126               4  world-music  
113381   70.792               4  world-music  
113504  104.905               4  world-music  
113600   91.439               4  world-music  
113804   84.252               4  world-music  

[4844 rows x 20 columns]

In [83]:
import os

In [84]:
done_spectrograms = [x.split('.')[0] for x in os.listdir('spectrograms')]
done_spectrograms[:10]

['002qpSULhHAw6DGqFxbaO1',
 '004iWPkSRbvOEvAPLWHl9M',
 '005U5ZHLoA4OEkWewAa32S',
 '006c9li2Mybyg5vm6doEfO',
 '009MGoCC568mI1yvsbmTxw',
 '00BHbc5GB5d35gsi8IsmZl',
 '00btR3u8FwO3Ip97Az3nZM',
 '00GVRTIWMjYwwHEjTLclgf',
 '00IjIaUaMCFG5gPE4PrDdG',
 '00isIFJWVpXIQ8HkGICSQp']

In [85]:
original_dataset_with_lyric_and_spec_data = original_dataset_with_lyric_data[original_dataset_with_lyric_data['track_id'].isin(done_spectrograms)]
original_dataset_with_lyric_and_spec_data

track_id                  artists  \
25      6D33wCKzWtNEgOovgeVJ7r               Jason Mraz   
29      2qESE1ZeWly7I3YjyTXmXh               Jason Mraz   
1302    1Wb09hTo6O41UzdOq7Pd2i              The Bamboos   
1452    0rnDmgcZvn9WPsOPqHbt16                  Osibisa   
1708    2yLm7Y9foI71By8rAdYsFE               Dos Santos   
...                        ...                      ...   
113373  0Z6NbNX43bPaHylvR2yvCV         Michael W. Smith   
113375  2YEJL2fwTq6RpH5PtdQfge         Michael W. Smith   
113381  7GwYyLNFyAsSsmt2aa0z6u         Michael W. Smith   
113504  5UjaOsrdoI4shw9gM2eNPC  Buena Vista Social Club   
113804  11TMcTS3iao1dvMogUSQVk  Buena Vista Social Club   

                      album_name                      track_name  popularity  \
25              Mellow Adult Pop                      Bella Luna           1   
29        Perfect Christmas Hits               Winter Wonderland           0   
1302    Hard Up (Deluxe Version)                         Hard Up          12   
1452                  Ojah Awake                      Ojah Awake           9   
1708                  Dos Santos                     El Pescador          17   
...                          ...                             ...         ...   
113373         Christmas at Home  Christmas Is Here - Radio Edit           1   
113375         Christmas at Home                    God with God           1   
113381         Christmas at Home                Freeze The Frame           1   
113504   Buena Vista Social Club               El Cuarto de Tula          14   
113804   Buena Vista Social Club           De Camino a la Vereda          11   

        duration_ms  explicit  danceability  energy  key  loudness  mode  \
25           302346     False         0.755   0.454    9    -9.609     0   
29           131760     False         0.620   0.309    5    -9.209     1   
1302         255227     False         0.782   0.922   11    -4.028     0   
1452         296093     False         0.581   0.709    2   -13.307     1   
1708         213186     False         0.562   0.722    4    -5.625     0   
...             ...       ...           ...     ...  ...       ...   ...   
113373       181143     False         0.226   0.279    0    -8.730     1   
113375       250859     False         0.226   0.388    8    -8.440     1   
113381       231873     False         0.392   0.285    5   -11.236     1   
113504       445426     False         0.546   0.715    9   -11.927     1   
113804       303973     False         0.630   0.462    3   -10.792     1   

        speechiness  acousticness  instrumentalness  liveness  valence  \
25           0.0352       0.75700          0.000000    0.2360    0.330   
29           0.0495       0.78800          0.000000    0.1460    0.664   
1302         0.0497       0.00655          0.011800    0.0728    0.761   
1452         0.0436       0.02680          0.232000    0.0398    0.816   
1708         0.0280       0.01320          0.897000    0.1140    0.887   
...             ...           ...               ...       ...      ...   
113373       0.0299       0.73800          0.000000    0.1410    0.354   
113375       0.0314       0.53500          0.000000    0.1030    0.158   
113381       0.0309       0.69400          0.000000    0.1100    0.212   
113504       0.0459       0.62100          0.000218    0.2940    0.850   
113804       0.0406       0.84900          0.000186    0.1250    0.963   

          tempo  time_signature  track_genre  
25      120.060               4     acoustic  
29      145.363               4     acoustic  
1302    104.015               4     afrobeat  
1452    132.096               4     afrobeat  
1708    100.747               4     afrobeat  
...         ...             ...          ...  
113373  183.600               3  world-music  
113375  114.126               4  world-music  
113381   70.792               4  world-music  
113504  104.905               4  world-music  
113804   84.252               4  

In [86]:
import numpy as np
final_dataset_combined_outputs = original_dataset_with_lyric_and_spec_data.copy()

final_dataset_combined_outputs['y'] = original_dataset_with_lyric_and_spec_data.apply(lambda x: np.array([*x[8:10], *x[13:18]], dtype=np.float32), axis=1)

final_dataset_combined_outputs

track_id                  artists  \
25      6D33wCKzWtNEgOovgeVJ7r               Jason Mraz   
29      2qESE1ZeWly7I3YjyTXmXh               Jason Mraz   
1302    1Wb09hTo6O41UzdOq7Pd2i              The Bamboos   
1452    0rnDmgcZvn9WPsOPqHbt16                  Osibisa   
1708    2yLm7Y9foI71By8rAdYsFE               Dos Santos   
...                        ...                      ...   
113373  0Z6NbNX43bPaHylvR2yvCV         Michael W. Smith   
113375  2YEJL2fwTq6RpH5PtdQfge         Michael W. Smith   
113381  7GwYyLNFyAsSsmt2aa0z6u         Michael W. Smith   
113504  5UjaOsrdoI4shw9gM2eNPC  Buena Vista Social Club   
113804  11TMcTS3iao1dvMogUSQVk  Buena Vista Social Club   

                      album_name                      track_name  popularity  \
25              Mellow Adult Pop                      Bella Luna           1   
29        Perfect Christmas Hits               Winter Wonderland           0   
1302    Hard Up (Deluxe Version)                         Hard Up          12   
1452                  Ojah Awake                      Ojah Awake           9   
1708                  Dos Santos                     El Pescador          17   
...                          ...                             ...         ...   
113373         Christmas at Home  Christmas Is Here - Radio Edit           1   
113375         Christmas at Home                    God with God           1   
113381         Christmas at Home                Freeze The Frame           1   
113504   Buena Vista Social Club               El Cuarto de Tula          14   
113804   Buena Vista Social Club           De Camino a la Vereda          11   

        duration_ms  explicit  danceability  energy  key  ...  mode  \
25           302346     False         0.755   0.454    9  ...     0   
29           131760     False         0.620   0.309    5  ...     1   
1302         255227     False         0.782   0.922   11  ...     0   
1452         296093     False         0.581   0.709    2  ...     1   
1708         213186     False         0.562   0.722    4  ...     0   
...             ...       ...           ...     ...  ...  ...   ...   
113373       181143     False         0.226   0.279    0  ...     1   
113375       250859     False         0.226   0.388    8  ...     1   
113381       231873     False         0.392   0.285    5  ...     1   
113504       445426     False         0.546   0.715    9  ...     1   
113804       303973     False         0.630   0.462    3  ...     1   

        speechiness  acousticness  instrumentalness  liveness  valence  \
25           0.0352       0.75700          0.000000    0.2360    0.330   
29           0.0495       0.78800          0.000000    0.1460    0.664   
1302         0.0497       0.00655          0.011800    0.0728    0.761   
1452         0.0436       0.02680          0.232000    0.0398    0.816   
1708         0.0280       0.01320          0.897000    0.1140    0.887   
...             ...           ...               ...       ...      ...   
113373       0.0299       0.73800          0.000000    0.1410    0.354   
113375       0.0314       0.53500          0.000000    0.1030    0.158   
113381       0.0309       0.69400          0.000000    0.1100    0.212   
113504       0.0459       0.62100          0.000218    0.2940    0.850   
113804       0.0406       0.84900          0.000186    0.1250    0.963   

          tempo  time_signature  track_genre  \
25      120.060               4     acoustic   
29      145.363               4     acoustic   
1302    104.015               4     afrobeat   
1452    132.096               4     afrobeat   
1708    100.747               4     afrobeat   
...         ...             ...          ...   
113373  183.600               3  world-music   
113375  114.126               4  world-music   
113381   70.792               4  world-music   
113504  104.905               4  world-music   
113804   84.252               4  world-music   

                                 

In [87]:
final_dataset_combined_outputs.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre', 'y'],
      dtype='object')

In [88]:
dataset_with_original_outputs = final_dataset_combined_outputs[['track_id', 'y']]

In [89]:
sentiment = pd.read_csv("dataset_sentiment.csv")
sentiment.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'compound'], inplace=True)
sentiment.columns

Index(['Artist', 'Song', 'Lyrics', 'negative', 'neutral', 'positive'], dtype='object')

In [90]:
lyrics_with_trackid_for_merge = lyrics_with_trackid.copy()
lyrics_with_trackid_for_merge['SongArtist'] = lyrics_with_trackid.apply(lambda x: x[0] + x[1], axis=1)
lyrics_with_trackid_for_merge.drop(columns=['Artist', 'Song', 'Lyrics'], inplace=True)
print(lyrics_with_trackid_for_merge.columns)

sentiment_for_merge = sentiment.copy()
sentiment_for_merge['SongArtist'] = sentiment.apply(lambda x: x[0] + x[1], axis=1)
sentiment_for_merge.drop(columns=['Artist', 'Song', 'Lyrics'], inplace=True)
sentiment_for_merge

Index(['track_id', 'SongArtist'], dtype='object')


negative  neutral  positive  \
0        0.135    0.681     0.184   
1        0.065    0.729     0.206   
2        0.079    0.830     0.091   
3        0.096    0.679     0.224   
4        0.051    0.734     0.215   
...        ...      ...       ...   
8729     0.143    0.518     0.339   
8730     0.000    1.000     0.000   
8731     0.339    0.594     0.067   
8732     0.000    1.000     0.000   
8733     0.289    0.616     0.095   

                                             SongArtist  
0                             Kidz Bop KidsGhostbusters  
1     Creedence Clearwater RevivalHave You Ever Seen...  
2                           All Time LowBlinding Lights  
3                                       BastillePompeii  
4                              Bryan AdamsSummer Of '69  
...                                                 ...  
8729                       High ContrastCalling My Name  
8730                               Paul KalkbrennerTief  
8731                             HypocrisyA Coming Race  
8732                                   Chloe AgnewSigma  
8733  Dan Vapid & the CheatsI Wanna Go to Machu Picc...  

[8734 rows x 4 columns]

In [91]:
sentiment_with_trackid = lyrics_with_trackid_for_merge.merge(sentiment_for_merge, left_on='SongArtist', right_on='SongArtist')
sentiment_with_trackid.drop_duplicates(inplace=True)
sentiment_with_trackid

track_id  \
0      5IWLGZJR6d8pl5a5tka18u   
1      49oArb5U9DsUXpPSjDPsob   
2      3bkgyThZ4ImhlQNgVRo850   
3      3oaqIiIIu9KUrfqE4AeT93   
4      1zzwcBhUh3TqB2sVJWH84i   
...                       ...   
33223  6x0LElzW1utVgphlTnqsX5   
33224  6PWDT5ZY8Fz5AZTu9CAeTy   
33225  7KDZ0tye2U1ImgVbr36eKp   
33226  7oqZVbE2W4MCoMS34PPDr3   
33227  3mUfADjtWU3XnQW2FPtBch   

                                              SongArtist  negative  neutral  \
0                              Kidz Bop KidsGhostbusters     0.135    0.681   
1      Creedence Clearwater RevivalHave You Ever Seen...     0.065    0.729   
2                            All Time LowBlinding Lights     0.079    0.830   
3                                        BastillePompeii     0.096    0.679   
4                               Bryan AdamsSummer Of '69     0.051    0.734   
...                                                  ...       ...      ...   
33223                       High ContrastCalling My Name     0.143    0.518   
33224                               Paul KalkbrennerTief     0.000    1.000   
33225                             HypocrisyA Coming Race     0.339    0.594   
33226                                   Chloe AgnewSigma     0.000    1.000   
33227  Dan Vapid & the CheatsI Wanna Go to Machu Picc...     0.289    0.616   

       positive  
0         0.184  
1         0.206  
2         0.091  
3         0.224  
4         0.215  
...         ...  
33223     0.339  
33224     0.000  
33225     0.067  
33226     0.000  
33227     0.095  

[3936 rows x 5 columns]

In [92]:
sentiment_x = sentiment_with_trackid[['track_id', 'negative', 'neutral', 'positive']]
sentiment_x

track_id  negative  neutral  positive
0      5IWLGZJR6d8pl5a5tka18u     0.135    0.681     0.184
1      49oArb5U9DsUXpPSjDPsob     0.065    0.729     0.206
2      3bkgyThZ4ImhlQNgVRo850     0.079    0.830     0.091
3      3oaqIiIIu9KUrfqE4AeT93     0.096    0.679     0.224
4      1zzwcBhUh3TqB2sVJWH84i     0.051    0.734     0.215
...                       ...       ...      ...       ...
33223  6x0LElzW1utVgphlTnqsX5     0.143    0.518     0.339
33224  6PWDT5ZY8Fz5AZTu9CAeTy     0.000    1.000     0.000
33225  7KDZ0tye2U1ImgVbr36eKp     0.339    0.594     0.067
33226  7oqZVbE2W4MCoMS34PPDr3     0.000    1.000     0.000
33227  3mUfADjtWU3XnQW2FPtBch     0.289    0.616     0.095

[3936 rows x 4 columns]

In [93]:
dataset = final_dataset_combined_outputs.merge(sentiment_x, on='track_id')
dataset

track_id                  artists  \
0     6D33wCKzWtNEgOovgeVJ7r               Jason Mraz   
1     6D33wCKzWtNEgOovgeVJ7r               Jason Mraz   
2     2qESE1ZeWly7I3YjyTXmXh               Jason Mraz   
3     2qESE1ZeWly7I3YjyTXmXh               Jason Mraz   
4     1Wb09hTo6O41UzdOq7Pd2i              The Bamboos   
...                      ...                      ...   
4546  2YEJL2fwTq6RpH5PtdQfge         Michael W. Smith   
4547  7GwYyLNFyAsSsmt2aa0z6u         Michael W. Smith   
4548  5UjaOsrdoI4shw9gM2eNPC  Buena Vista Social Club   
4549  11TMcTS3iao1dvMogUSQVk  Buena Vista Social Club   
4550  11TMcTS3iao1dvMogUSQVk  Buena Vista Social Club   

                    album_name             track_name  popularity  \
0             Mellow Adult Pop             Bella Luna           1   
1             Mellow Adult Pop             Bella Luna           1   
2       Perfect Christmas Hits      Winter Wonderland           0   
3       Perfect Christmas Hits      Winter Wonderland           1   
4     Hard Up (Deluxe Version)                Hard Up          12   
...                        ...                    ...         ...   
4546         Christmas at Home           God with God           1   
4547         Christmas at Home       Freeze The Frame           1   
4548   Buena Vista Social Club      El Cuarto de Tula          14   
4549   Buena Vista Social Club  De Camino a la Vereda          11   
4550   Buena Vista Social Club  De Camino a la Vereda          11   

      duration_ms  explicit  danceability  energy  key  ...  instrumentalness  \
0          302346     False         0.755   0.454    9  ...          0.000000   
1          302346     False         0.755   0.454    9  ...          0.000000   
2          131760     False         0.620   0.309    5  ...          0.000000   
3          131760     False         0.620   0.309    5  ...          0.000000   
4          255227     False         0.782   0.922   11  ...          0.011800   
...           ...       ...           ...     ...  ...  ...               ...   
4546       250859     False         0.226   0.388    8  ...          0.000000   
4547       231873     False         0.392   0.285    5  ...          0.000000   
4548       445426     False         0.546   0.715    9  ...          0.000218   
4549       303973     False         0.630   0.462    3  ...          0.000186   
4550       303973     False         0.630   0.462    3  ...          0.000186   

      liveness  valence    tempo  time_signature  track_genre  \
0       0.2360    0.330  120.060               4     acoustic   
1       0.2360    0.330  120.060               4         rock   
2       0.1460    0.664  145.363               4     acoustic   
3       0.1460    0.664  145.363               4         rock   
4       0.0728    0.761  104.015               4     afrobeat   
...        ...      ...      ...             ...          ...   
4546    0.1030    0.158  114.126               4  world-music   
4547    0.1100    0.212   70.792               4  world-music   
4548    0.2940    0.850  104.905               4  world-music   
4549    0.1250    0.963   84.252               4  world-music   
4550    0.1250    0.963   84.252               4  world-music   

                                                      y  negative  neutral  \
0         [0.454, 9.0, 0.757, 0.0, 0.236, 0.33, 120.06]     0.056    0.592   
1         [0.454, 9.0, 0.757, 0.0, 0.236, 0.33, 120.06]     0.056    0.592   
2       [0.309, 5.0, 0.788, 0.0, 0.146, 0.664, 145.363]     0.122    0.682   
3       [0.309, 5.0, 0.788, 0.0, 0.146, 0.664, 145.363]     0.122    0.682   
4     [0.922, 11.0, 0.00655, 0.0118, 0.0728, 0.761, ...     0.164    0.723   
...                                                 ...       ...      ...   
4546    [0.388, 8.0, 0.535, 0.0, 0.103, 0.158, 114.126]     0.043    0.708   
4547      [0.285, 5.0, 0.694, 0.0, 0.11, 0.212, 70.792]     0.239    0.508   
4548  [0.715, 9.0, 0.621, 0.000218, 0.294, 0.85, 1

In [94]:
final_dataset = dataset[['track_id', 'y', 'negative', 'neutral', 'positive']].copy()
final_dataset['x_sentiment'] = final_dataset.apply(lambda x: np.array([x[2], x[3], x[4]]), axis=1)
final_dataset.drop(columns=['negative', 'neutral', 'positive'], inplace=True)
final_dataset

track_id  \
0     6D33wCKzWtNEgOovgeVJ7r   
1     6D33wCKzWtNEgOovgeVJ7r   
2     2qESE1ZeWly7I3YjyTXmXh   
3     2qESE1ZeWly7I3YjyTXmXh   
4     1Wb09hTo6O41UzdOq7Pd2i   
...                      ...   
4546  2YEJL2fwTq6RpH5PtdQfge   
4547  7GwYyLNFyAsSsmt2aa0z6u   
4548  5UjaOsrdoI4shw9gM2eNPC   
4549  11TMcTS3iao1dvMogUSQVk   
4550  11TMcTS3iao1dvMogUSQVk   

                                                      y            x_sentiment  
0         [0.454, 9.0, 0.757, 0.0, 0.236, 0.33, 120.06]  [0.056, 0.592, 0.353]  
1         [0.454, 9.0, 0.757, 0.0, 0.236, 0.33, 120.06]  [0.056, 0.592, 0.353]  
2       [0.309, 5.0, 0.788, 0.0, 0.146, 0.664, 145.363]  [0.122, 0.682, 0.196]  
3       [0.309, 5.0, 0.788, 0.0, 0.146, 0.664, 145.363]  [0.122, 0.682, 0.196]  
4     [0.922, 11.0, 0.00655, 0.0118, 0.0728, 0.761, ...  [0.164, 0.723, 0.113]  
...                                                 ...                    ...  
4546    [0.388, 8.0, 0.535, 0.0, 0.103, 0.158, 114.126]  [0.043, 0.708, 0.249]  
4547      [0.285, 5.0, 0.694, 0.0, 0.11, 0.212, 70.792]  [0.239, 0.508, 0.254]  
4548  [0.715, 9.0, 0.621, 0.000218, 0.294, 0.85, 104...    [0.0, 0.963, 0.037]  
4549  [0.462, 3.0, 0.849, 0.000186, 0.125, 0.963, 84...  [0.028, 0.887, 0.086]  
4550  [0.462, 3.0, 0.849, 0.000186, 0.125, 0.963, 84...    [0.0, 0.986, 0.014]  

[4551 rows x 3 columns]

In [95]:
import pickle

with open("final_dataset.pickle", "wb") as f:
    pickle.dump(final_dataset, f)

In [96]:
with open("final_dataset.pickle", "rb") as f:
    dataset = pickle.load(f)

track_ids = list(dataset['track_id'])
y = dataset['y'].to_numpy()
y = np.array([x for x in y])
y

array([[4.54000e-01, 9.00000e+00, 7.57000e-01, ..., 2.36000e-01,
        3.30000e-01, 1.20060e+02],
       [4.54000e-01, 9.00000e+00, 7.57000e-01, ..., 2.36000e-01,
        3.30000e-01, 1.20060e+02],
       [3.09000e-01, 5.00000e+00, 7.88000e-01, ..., 1.46000e-01,
        6.64000e-01, 1.45363e+02],
       ...,
       [7.15000e-01, 9.00000e+00, 6.21000e-01, ..., 2.94000e-01,
        8.50000e-01, 1.04905e+02],
       [4.62000e-01, 3.00000e+00, 8.49000e-01, ..., 1.25000e-01,
        9.63000e-01, 8.42520e+01],
       [4.62000e-01, 3.00000e+00, 8.49000e-01, ..., 1.25000e-01,
        9.63000e-01, 8.42520e+01]], dtype=float32)

In [97]:
from PIL import Image

x_img = np.empty((y.shape[0], 23, 31, 3), dtype=np.uint8)

for i, track_id in enumerate(track_ids):
    img = Image.open(os.path.join('spectrograms', track_id + '.png'))
    im = np.array(img)

    rgb_im = im[:,:,:3]

    x_img[i] = rgb_im


In [98]:
x_sentiment = dataset['x_sentiment'].to_numpy()
x_sentiment = np.array([x for x in x_sentiment])
print(x_sentiment)

[[0.056 0.592 0.353]
 [0.056 0.592 0.353]
 [0.122 0.682 0.196]
 ...
 [0.    0.963 0.037]
 [0.028 0.887 0.086]
 [0.    0.986 0.014]]


In [100]:
print(x_sentiment.shape, x_img.shape, y.shape)

(4551, 3) (4551, 23, 31, 3) (4551, 7)


In [101]:
np.savez("dataset.npz", x_sent=x_sentiment, x_img=x_img, y=y)